# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Tests"
  lane :tests do
    scan(
    	scheme: "CircleCi",
	result_bundle: true,
    	devices: ["iPhone 8"]
    )
  end

  desc "Push to testflight"
  lane :beta do
    match(type: "appstore",
          app_identifier: "com.pillartechnology.CircleCi",
          readonly: true)
    gym(scheme: "CircleCi",
        workspace: "CircleCi.xcworkspace",
        clean: true)
    pilot()
  end
end
